### ISSUE TITLE
Could not resolve project :materialdialog

### ISSUE THREAD

**Issue by AnserBaby** [shank03/Schedule-Dark-Theme#1]
Could not resolve project :materialdialog
Could not resolve project :fastscroller

**Comment by shank03** [comment]
They are public library.

You need to add those dependencies :)

**Comment by AnserBaby** [comment]
> They are public library.
> 
> You need to add those dependencies :)

soga，thank

**Comment by AnserBaby** [comment]
> They are public library.
> 
> You need to add those dependencies :)

how can i find they?
